# EdgeOne whoami Docker build pipeline 
# Example: germanedge-docker/whoami:1.0
# dockerRegistry: "artifactory.new-solutions.com" -> image container registry service

name: "e1-whoami_$(Date:yyyyMMdd)$(Rev:.r)"

variables:
  dockerId: "edge-one"  # Docker-ID for container registry service
  imageName: "whoami"  # name of the image 

trigger:
- master
- develop

pr: none

jobs:
- job: 'DockerLinuxMaster'
  condition: eq(variables['build.SourceBranchName'], 'master')
  displayName: 'creates a whoami Docker for Linux'
  pool:
    name: 'Hosted Ubuntu 1604'
  steps:
  - task: Docker@2
    displayName: 'Build and Push the image'
    inputs:
      containerRegistry: 'germanedge-docker.artifactory'
      repository: '$(dockerId)/$(imageName)'
      command: 'buildAndPush'
      Dockerfile: 'linux/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        master
        latest

- job: 'DockerLinux'
  condition: eq(variables['build.SourceBranchName'], 'develop')
  displayName: 'creates a whoami Docker for Linux'
  pool:
    name: 'Hosted Ubuntu 1604'
  steps:
  - task: Docker@2
    displayName: 'Build and Push the image'
    inputs:
      containerRegistry: 'germanedge-docker.artifactory'
      repository: '$(dockerId)/$(imageName)'
      command: 'buildAndPush'
      Dockerfile: 'linux/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        develop
        latest